
# Stage 1: base images
FROM node:lts-alpine as base

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

WORKDIR /home/node/app

# setup pnpm
RUN npm install -g pnpm@6.11.5 nodemon

USER node

CMD pnpm config set store-dir /home/node/.pnpm-store \
    && pnpm i --shamefully-hoist \
    && nodemon
#    && while true; do HOST=0.0.0.0 nodemon; sleep 2; done
