
# Stage 1: base images
FROM node:lts-alpine as base

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

WORKDIR /home/node/app

# setup pnpm
RUN npm install -g pnpm

USER node

CMD pnpm i \
    && while true; do npm start; sleep 2; done
