
# Stage 1: base images
FROM node:lts-alpine as base

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

WORKDIR /home/node/app

# setup pnpm
RUN npm install -g pnpm nodemon

USER node

CMD pnpm i \
    && nodemon
#    && while true; do HOST=0.0.0.0 nodemon; sleep 2; done
